/**
 * _manifest.js — Source of truth para ordem GRADE
 * 58 slides conforme _list.txt Aulas_core
 */

export const slides = [
  { id: 's-01', file: '01.html', archetype: 'title', headline: 'CORE GRADE — A coragem na incerteza', panelState: null },
  { id: 's-02', file: '02.html', archetype: 'comparison', headline: 'A zona cinzenta é a regra.', panelState: null },
  { id: 's-05', file: '04.html', archetype: 'flow', headline: 'O motor do GRADE', panelState: null },
  { id: 's-06', file: '05.html', archetype: 'comparison', headline: 'CAC reclassifica risco e muda a meta', panelState: null },
  { id: 's-03', file: '03.html', archetype: 'comparison', headline: 'O grande divisor: certeza ≠ força', panelState: null },
  { id: 's-09', file: '06.html', archetype: 'comparison', headline: 'CAC: leitura GRADE explícita', panelState: null },
  { id: 's-36', file: '07.html', archetype: 'comparison', headline: 'Do CAC à meta de LDL', panelState: null },
  { id: 's-08', file: '08.html', archetype: 'comparison', headline: 'Upgrade: quando a evidência sobe', panelState: null },
  { id: 's-11', file: '09.html', archetype: 'comparison', headline: 'Estatina vs aspirina: NNT muda com o CAC', panelState: null },
  { id: 's-10', file: '10.html', archetype: 'comparison', headline: 'CAC como staging cardiovascular', panelState: null },
  { id: 's-07', file: '11.html', archetype: 'comparison', headline: 'Indireção: quando a evidência não encaixa', panelState: null },
  { id: 's-61', file: '12.html', archetype: 'comparison', headline: 'Ácido bempedóico: de LDL para MACE', panelState: null },
  { id: 's-14', file: '13.html', archetype: 'comparison', headline: 'Três diretrizes, uma evidência: GRADE decide', panelState: null },
  { id: 's-43', file: '14.html', archetype: 'comparison', headline: 'SAMS não é causalidade — e muda o PICO', panelState: null },
  { id: 's-44', file: '15.html', archetype: 'comparison', headline: 'Mesmo HR, NNT diferente: o risco basal decide', panelState: null },
  { id: 's-63', file: '16.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-19', file: '17.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-47', file: '18.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-17', file: '19.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-18', file: '20.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-62', file: '21.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-64', file: '22.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-45', file: '23.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-50', file: '24.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-51', file: '25.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-52', file: '26.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-53', file: '27.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-54', file: '28.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-54b', file: '29.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-55', file: '30.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-56', file: '31.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-48', file: '32.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-65', file: '33.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-59', file: '34.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-57', file: '35.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-58', file: '36.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-04', file: '37.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-22', file: '38.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-23', file: '39.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-24', file: '40.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-25', file: '41.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-26', file: '42.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-27', file: '43.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-28', file: '44.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-29', file: '45.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-30', file: '46.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-31', file: '47.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-32', file: '48.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-33', file: '49.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-34', file: '50.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-35', file: '51.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-37', file: '52.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-38', file: '53.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-12', file: '54.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-39', file: '55.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-40', file: '56.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-41', file: '57.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-42', file: '58.html', archetype: 'comparison', headline: '', panelState: null },
];
