/**
 * _manifest.js — Source of truth para ordem Osteoporose
 * 71 slides (46 main + 25 appendix)
 */

export const slides = [
  { id: 's-01', file: '01.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-02', file: '02.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-03', file: '03.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-04', file: '04.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-05', file: '05.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-06', file: '06.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-12', file: '07.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-13', file: '08.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-17', file: '09.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-14', file: '10.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-19', file: '11.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-14b', file: '12.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-23', file: '13.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-22', file: '14.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-24', file: '15.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-25', file: '16.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-26', file: '17.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-28', file: '18.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-29', file: '19.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-30', file: '20.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-31', file: '21.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-73', file: '22.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-74', file: '23.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-75', file: '24.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-32', file: '25.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-33', file: '26.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-35', file: '27.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-08', file: '28.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-08b', file: '29.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-36', file: '30.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-37', file: '31.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-38', file: '32.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-39', file: '33.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-40', file: '34.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-41', file: '35.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-42', file: '36.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-43', file: '37.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-44', file: '38.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-47', file: '39.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-46', file: '40.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-48', file: '41.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-49', file: '42.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-50', file: '43.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-45', file: '44.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-99', file: '45.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-09', file: '46.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-10', file: '47.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-11', file: '48.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-51', file: '49.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-52', file: '50.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-53', file: '51.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-54', file: '52.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-55', file: '53.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-56', file: '54.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-57', file: '55.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-58', file: '56.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-59', file: '57.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-60', file: '58.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-61', file: '59.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-62', file: '60.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-63', file: '61.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-64', file: '62.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-65', file: '63.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-66', file: '64.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-67', file: '65.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-68', file: '66.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-69', file: '67.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-70', file: '68.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-71', file: '69.html', archetype: 'comparison', headline: '', panelState: null },
  { id: 's-72', file: '70.html', archetype: 'comparison', headline: '', panelState: null },
];
